- name: authenticate gcloud service account
  shell: gcloud auth activate-service-account --key-file=/tmp/cloud_config.yml

- name: Gcloud project setting
  shell: gcloud config set project {{ project_id }}

- name: Checking gcloud config list
  shell: gcloud config list