---

## Following variables requierd to perform action on AWS instance using chaostoolkit, chaostoolkit-aws driver
LABEL_NAME: "app" # label name
NAME_SPACE: "default" # name space 
APP_ENDPOINT: "localhost" ## you define ingress or service endpoint
chaos_prob: "count_pods" ## chaos probe validation
chaos_action: "terminate_pods"    ## stop_instance,
chaos_experiment: "k8-pod-delete"    ## stop_instance,
PERCENTAGE: "50" ## percentage pod to be terminated
file: pod-app-kill-count.j2 ## pod-app-kill-count.j2 (To terminate pod on k8)
