---
apiVersion: v1
kind: Pod
metadata:
  name: chaos-runner
  labels:
    name: chaos-runner
spec:
  serviceAccountName: chaos-operator
  restartPolicy: Never
  containers:
  - name: ansibletest
    image: openebs/ansible-runner:ci
    imagePullPolicy: Always
    env:
      - name: ANSIBLE_STDOUT_CALLBACK
        value: default

      - name: APP_NAMESPACE
        value: default 

      - name: APP_LABEL
        value: 'app=nginx'

      - name: CHAOSENGINE
        value: "engine-nginx"

      - name: EXPERIMENT_LIST
        value: "pod-delete,container-kill"

    command: ["/bin/bash"]
    args: ["-c", "ansible-playbook ./executor/test.yml -i /etc/ansible/hosts -vv; exit 0"]

