- name: Get configmap names from Chaos Engine
  shell: >
    kubectl get chaosengine {{ c_engine }} -n {{ c_app_ns }} -o json | jq '.spec.experiments[] | select(.name == "{{ c_experiment_name }}") | .spec.components.configMaps[{{item}}].name' | tr -d "\""
  args:
    executable: /bin/bash
  register: engine_cmap_name

- name: Get configmap mountPath from Chaos Engine
  shell: >
    kubectl get chaosengine {{ c_engine }} -n {{ c_app_ns }} -o json | jq '.spec.experiments[] | select(.name == "{{ c_experiment_name }}") | .spec.components.configMaps[{{item}}].mountPath' | tr -d "\""
  args:
    executable: /bin/bash
  register: engine_cmap_mountPath

- name: Append engine configmap
  set_fact:
    c_map_details: "{{c_map_details | combine({engine_cmap_name.stdout : engine_cmap_mountPath.stdout})}}"
