- name: Get configmap names from Chaos Experiment
  shell: >
    kubectl get chaosexperiment {{ c_experiment_name }} -o json
    | jq '.spec.definition.configmaps[{{item}}].name' | tr -d "\""
  args:
    executable: /bin/bash
  register: experiment_cmap_name

- name: Get configmap mountPath from Chaos Experiment
  shell: >
    kubectl get chaosexperiment {{ c_experiment_name }} -o json
    | jq '.spec.definition.configmaps[{{item}}].mountPath' | tr -d "\""
  args:
    executable: /bin/bash
  register: experiment_cmap_mountPath

- name: Append experiment configMap
  set_fact:
    c_map_details: "{{c_map_details | combine({experiment_cmap_name.stdout : experiment_cmap_mountPath.stdout})}}"
